import type { AgentDefinition } from "./contracts.js";
import { DESKTOP_AGENT_ID } from "./desktop-agent-identity.js";
import { DESKTOP_ROOT_AGENT_OUTPUT_CONTRACT } from "./desktop-root-agent-output-contract.js";
import {
  DESKTOP_ROOT_AGENT_PROMPT,
  DESKTOP_ROOT_AGENT_PROMPT_ZH,
  DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V7,
  DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_1,
  DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V6,
  DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V5,
  DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V4,
  DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V3,
  DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V2,
  DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V1,
} from "./desktop-root-agent-prompt.js";
import { DESKTOP_ROOT_AGENT_TOOL_VISIBILITY } from "./desktop-root-agent-tool-visibility.js";
import { DESKTOP_ROOT_AGENT_TURN_POLICY } from "./desktop-root-agent-turn-policy.js";

export const DESKTOP_ROOT_AGENT: AgentDefinition = {
  agentId: DESKTOP_AGENT_ID,
  displayName: "Desktop Agent",
  prompt: DESKTOP_ROOT_AGENT_PROMPT,
  turnPolicy: DESKTOP_ROOT_AGENT_TURN_POLICY,
  outputContract: DESKTOP_ROOT_AGENT_OUTPUT_CONTRACT,
  toolVisibilityProfile: DESKTOP_ROOT_AGENT_TOOL_VISIBILITY,
};

// 简体中文提示词变体定义：供运行时目录解析 zh-v1 引用与恢复历史 run。
export const DESKTOP_ROOT_AGENT_ZH: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_ZH,
};

export const DESKTOP_ROOT_AGENT_LEGACY_PROMPT_VERSION_1: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_1,
};

export const DESKTOP_ROOT_AGENT_LEGACY_PROMPT_VERSION_V7: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V7,
};

export const DESKTOP_ROOT_AGENT_LEGACY_PROMPT_VERSION_V6: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V6,
};

export const DESKTOP_ROOT_AGENT_LEGACY_PROMPT_VERSION_V5: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V5,
};

export const DESKTOP_ROOT_AGENT_LEGACY_PROMPT_VERSION_V4: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V4,
};

export const DESKTOP_ROOT_AGENT_LEGACY_PROMPT_VERSION_V3: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V3,
};

export const DESKTOP_ROOT_AGENT_LEGACY_PROMPT_VERSION_V1: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V1,
};

export const DESKTOP_ROOT_AGENT_LEGACY_PROMPT_VERSION_V2: AgentDefinition = {
  ...DESKTOP_ROOT_AGENT,
  prompt: DESKTOP_ROOT_AGENT_PROMPT_LEGACY_VERSION_V2,
};
