import path from "node:path";
import test from "node:test";
import { readAppSource, readPanelUiSource, readPanelUiStyle } from "./panel-structure-test-utils.js";

test("multi Agent workspace uses a linear answer transcript with click-to-open details", async () => {
  const [multiAgentWorkspace, deepView, transcriptTimeline, deepStyles] = await Promise.all([
    readPanelUiSource(path.join("components", "multi-agent-workspace.tsx")),
    readPanelUiSource(path.join("components", "deep-view.tsx")),
    readPanelUiSource(path.join("components", "transcript-timeline.tsx")),
    readPanelUiStyle("deep-view.css"),
  ]);

  includes(multiAgentWorkspace, "<DeepView");
  includes(multiAgentWorkspace, "<DeepWorkItemDetailPanel");
  includes(multiAgentWorkspace, "selectedComposerModel");
  includes(multiAgentWorkspace, "assistantModel");
  includes(multiAgentWorkspace, "selectedWorkItem");
  includes(multiAgentWorkspace, "setSelectedWorkItem");
  includes(multiAgentWorkspace, "deepRunWorkItemExists");
  includes(multiAgentWorkspace, "with-work-detail");
  includes(multiAgentWorkspace, "ChatInputBar");
  includes(multiAgentWorkspace, "props.view !== undefined && selectedWorkItem !== undefined");
  includes(multiAgentWorkspace, "onStartConfirmedRun={props.onStartConfirmedRun}");
  includes(multiAgentWorkspace, "onResynthesize={props.onResynthesize}");
  includes(multiAgentWorkspace, "onStopRun={props.onStopRun}");
  includes(multiAgentWorkspace, "resynthesisBusy={props.resynthesisBusy || props.childOperationBusyId !== undefined}");
  excludes(multiAgentWorkspace, "readonly runs:");
  excludes(multiAgentWorkspace, "readonly activeRunId?");
  excludes(multiAgentWorkspace, "selectedWorkflowItem");
  excludes(multiAgentWorkspace, "setSelectedWorkflowItem");
  excludes(multiAgentWorkspace, "selectedChildRunId");
  excludes(multiAgentWorkspace, "selectedNode");
  excludes(multiAgentWorkspace, "with-workflow-detail");
  excludes(multiAgentWorkspace, "with-task-sidebar");
  excludes(multiAgentWorkspace, "with-node-inspector");
  excludes(multiAgentWorkspace, "selectedWorkItem.kind === \"child_agent\"");
  excludes(multiAgentWorkspace, "<DeepParentWorkflowPane");
  excludes(multiAgentWorkspace, "<DeepWorkflowDetailPanel");
  excludes(multiAgentWorkspace, "<DeepTaskSidebar");
  excludes(multiAgentWorkspace, "<DeepCollaborationNodeIndex");
  excludes(multiAgentWorkspace, "<DeepNodeInspector");
  excludes(multiAgentWorkspace, "<DeepRunTree");

  includes(deepView, "export type DeepPlanConfirmationViewModel");
  includes(deepView, "export type DeepRunTranscriptViewModel");
  includes(deepView, "export type DeepRunTranscriptBlock");
  includes(deepView, "export type DeepWorkItemDetailViewModel");
  includes(deepView, "export type DeepSelectedWorkItem");
  includes(deepView, "readonly blocks: readonly DeepRunTranscriptBlock[]");
  includes(deepView, "readonly children: readonly DeepRunChildSummaryViewModel[]");
  includes(deepView, "readonly worklineItems: readonly DeepWorklineItemViewModel[]");
  includes(deepView, "function DeepPlanConfirmationCard");
  includes(deepView, "function DeepRunTranscriptPane");
  includes(deepView, "function DeepRunTranscriptChildListBlock");
  includes(deepView, "AssistantMessageLabel");
  includes(deepView, "assistantModel?: AssistantModelBadge");
  includes(deepView, "AgentWorkTimeline");
  includes(deepView, "ActivityItem");
  includes(deepView, "export function DeepWorkItemDetailPanel");
  includes(deepView, "function deepPlanConfirmationViewModel");
  includes(deepView, "function deepRunTranscriptViewModel");
  includes(deepView, "function deepRunTranscriptBlocks");
  includes(deepView, "function deepConversationTranscriptBlocks");
  includes(deepView, "function managerDecisionComesBeforeChildren");
  includes(deepView, "function isChildLifecycleEvent");
  includes(deepView, "return view.liveProjection.decision?.summary;");
  includes(deepView, "function detailTimelineView");
  includes(deepView, "function detailActivityItem");
  includes(deepView, "function activityStatusBadge");
  includes(deepView, "function childAgentImportantSignal");
  includes(deepView, "function childAgentSignalText");
  includes(deepView, "function visibleWorkflowStatusLabel");
  includes(deepView, "function meaningfulChildResultText");
  includes(deepView, "function isNaturalChildStateText");
  includes(deepView, "function compactWorklineText");
  includes(deepView, "function childDetailWorklineItems");
  includes(deepView, "type DeepChildAgentWorkflowSegment");
  includes(deepView, "function DeepChildAgentWorkflow");
  includes(deepView, "function deepChildWorkflowHasRenderableSegments");
  includes(deepView, "function deepChildAgentWorkflowSegments");
  includes(deepView, "function appendExecutionSegmentWorkflow");
  includes(deepView, "function toolActivityWorkflowSegment");
  includes(deepView, "function childMaterialResultText");
  includes(deepView, "const summary = meaningfulChildResultText(child.latestResult, child.objective);");
  includes(deepView, "readonly findings: readonly string[]");
  includes(deepView, "readonly evidenceRefs: readonly string[]");
  includes(deepView, "发现：");
  includes(deepView, "不确定性：");
  includes(deepView, "证据：");
  includes(deepView, "export function deepRunWorkItemExists");
  includes(deepView, "function deepWorkItemDetailViewModel");
  includes(deepView, "function deepWorklineItems");
  includes(deepView, "function childRunWorklineItems");
  includes(deepView, "function childDetailVisibleWorklineItems");
  includes(deepView, "function isChildDetailConcreteActionItem");
  includes(deepView, "function childModelMessageWorklineItem");
  includes(deepView, "function childModelMessageText");
  includes(deepView, "function childToolCallWorklineItem");
  includes(deepView, "displayActivityItemsForNodes");
  includes(deepView, "function toolCallActivityItem");
  includes(deepView, "function toolCallExpandedSections");
  includes(deepView, "function toolCallBadges");
  includes(deepView, "call.summary ?? call.inputSummary");
  includes(deepView, "readonly expandedSections?: readonly ActivityExpandedSection[]");
  includes(deepView, "function executionSegmentWorklineItem");
  includes(deepView, "function runTranscriptWorkflowItems");
  includes(deepView, "function childAgentSummaryItems");
  includes(deepView, "function childAgentSummaryItem");
  includes(deepView, "conversation={props.conversation}");
  includes(deepView, "pendingGoal={props.pendingGoal}");
  includes(deepView, "deepIntakeChatItems(props.conversation.intakeTurns, props.intakeStatus)");
  includes(deepView, "liveChild?.workflowItems");
  includes(deepView, "liveChild?.latestResult");
  includes(deepView, "childRun.executionHistory");
  includes(deepView, "segment.modelMessages");
  includes(deepView, "<DeepChildAgentWorkflow");
  includes(deepView, "detail.child === undefined || !deepChildWorkflowHasRenderableSegments(detail.child, detail.worklineItems)");
  includes(deepView, "<RichText text={segment.text} />");
  includes(deepView, "collapsed={true}");
  excludes(deepView, "function childModelToolCallDecisionText");
  excludes(deepView, "function toolCallDecisionText");
  excludes(deepView, "模型发起");
  excludes(deepView, "<span>工作流</span>");
  excludes(deepView, "条模型输出");
  includes(deepView, "工具调用前说明");
  includes(deepView, "child.childRun");
  includes(deepView, "detail.child.pendingApproval");
  includes(deepView, "ChildTaskApproval");
  includes(deepView, "deep-child-task-approval");
  includes(deepView, "props.onChildMessage &&");
  includes(deepView, "补充给这个协作项");
  includes(deepView, "开始深度研究");
  includes(deepView, "重置计划");
  includes(deepView, "function DeepConclusionMessage");
  includes(deepView, "function DeepRuntimeHealthNotice");
  includes(deepView, "function runtimeHealthNoticeViewModel");
  includes(deepView, "readonly resynthesisBusy?: boolean");
  includes(deepView, "readonly onResynthesize?: () => void | Promise<void>;");
  includes(deepView, "readonly onStopRun?: () => void | Promise<void>;");
  includes(deepView, 'kind: "conclusion"');
  includes(deepView, "deep-compact-conclusion");
  includes(deepView, "重新综合");
  includes(deepView, "view.liveProjection.synthesis?.status === \"pending\"");
  includes(deepView, "health?.state !== \"stalled\" && health?.state !== \"orphaned\"");
  includes(deepView, "这次运行一段时间没有新进展");
  includes(deepView, "这次运行已失联");
  includes(deepView, "停止本次运行");
  excludes(deepView, "疑似卡住");
  includes(deepView, 'aria-label="助手回复"');
  includes(deepView, 'aria-label="计划确认"');
  includes(deepView, 'aria-label="详情"');
  includes(deepView, "chat-active-screen");
  includes(deepView, "chat-active-scroll");
  includes(deepView, "chat-active-grid");
  includes(deepView, "session-stream");
  includes(deepView, "deep-run-child-list-item");
  includes(deepView, 'role="list" aria-label="协作项"');
  includes(deepView, "onSelectWorkItem={props.onSelectWorkItem}");
  includes(deepView, "view={detailTimelineView(detail.worklineItems)}");
  includes(deepView, "执行记录");
  includes(deepView, "条动作");
  includes(deepView, "label: input.label");
  includes(deepView, 'kind: "child_agent_list"');
  excludes(deepView, "<Bot size={14} />");
  excludes(deepView, "function mergeToolWorklineItems");
  excludes(deepView, "function canMergeToolWorklineItems");
  excludes(deepView, "已合并连续工具调用");
  excludes(deepView, 'assistant-message-model">多 Agent');
  excludes(deepView, "type DeepRunTranscriptActivityItemViewModel");
  excludes(deepView, "function DeepRunTranscriptActivityBlock");
  excludes(deepView, "function runTranscriptTimelineView");
  excludes(deepView, "function runTranscriptActivityItem");
  excludes(deepView, "function runTranscriptActivityItems");
  excludes(deepView, "function childAgentWorklineItem");
  excludes(deepView, "function taskPlanWorklineTone");
  excludes(deepView, "function taskPlanToolKind");
  excludes(deepView, "selectedItemKey={props.selectedActivityKey}");
  excludes(deepView, "onSelectItem={props.onSelectActivity}");
  excludes(deepView, 'kind: "activity_timeline"');
  excludes(deepView, "function childTranscriptResultText");
  excludes(deepView, 'text: childActivityIntro(view.liveProjection.children)');
  excludes(deepView, 'text: `${child.title}：${result}`');
  excludes(deepView, "detail: child.latestResult ?? child.summary");
  excludes(deepView, "export type DeepRunConsoleViewModel");
  excludes(deepView, "function DeepRunConsolePane");
  excludes(deepView, "function deepRunConsoleViewModel");
  excludes(deepView, "function runConsoleTimelineView");
  excludes(deepView, "function runConsoleActivityItem");
  excludes(deepView, "function runConsoleWorklineItems");
  excludes(deepView, "function runConsoleWorkflowItems");
  excludes(deepView, "function DeepActivityLine");
  excludes(deepView, "formatShortTime");
  excludes(deepView, "formatToolCountSummary");
  excludes(deepView, "agent-activity-step deep-run-workflow-item");
  excludes(deepView, "deep-workline-title");
  excludes(deepView, "export type DeepAgentWorkflowViewModel");
  excludes(deepView, "export type DeepWorkflowItemViewModel");
  excludes(deepView, "export type DeepWorkflowDetailViewModel");
  excludes(deepView, "export type DeepSelectedWorkflowItem");
  excludes(deepView, "export function DeepParentWorkflowPane");
  excludes(deepView, "export function DeepWorkflowDetailPanel");
  excludes(deepView, "export function DeepTaskSidebar");
  excludes(deepView, "DeepTaskSidebarViewModel");
  excludes(deepView, "taskSidebarPlanItems");
  excludes(deepView, "export function deepAgentWorkflowViewModel");
  excludes(deepView, "export function workflowDetails");
  excludes(deepView, "export function workflowDetailViewModel");
  excludes(deepView, "export function defaultSelectedWorkflowItem");
  excludes(deepView, "export function managerStepDetailViewModels");
  excludes(deepView, "export function childTaskDetailViewModels");
  excludes(deepView, "export function synthesisDetailViewModel");
  excludes(deepView, "export function conclusionDetailViewModel");
  excludes(deepView, "DeepCollaborationNodeIndex");
  excludes(deepView, "DeepNodeInspector");
  excludes(deepView, "ChildNodeApproval");
  excludes(deepView, "deep-child-node-approval");
  excludes(deepView, 'aria-label="节点索引"');
  excludes(deepView, 'aria-label="节点详情"');
  excludes(deepView, 'aria-label="节点工作流程"');
  excludes(deepView, 'aria-label="任务侧栏"');
  excludes(deepView, 'title: "Manager"');
  excludes(deepView, 'title: "Synthesis"');
  excludes(deepView, 'title: "Conclusion"');
  excludes(deepView, "<DeepRunTree");
  excludes(deepView, 'from "./deep-run-tree"');
  excludes(deepView, "deep-tree-live-map");
  excludes(deepView, "DeepLiveTreeMap");
  excludes(deepView, 'className="deep-flow-canvas"');
  excludes(deepView, "workboardSummary");
  excludes(deepView, "deep-work-detail-timeline");
  excludes(deepView, "deep-work-detail-step");
  excludes(deepView, "workflowItemTone(");
  excludes(deepView, "model.workflowItems.map");
  excludes(deepView, "deep-run-child-card");
  excludes(deepView, "deep-run-child-grid");
  excludes(deepView, "deep-run-child-section");
  excludes(deepView, "model.result");
  excludes(deepView, "deep-run-result");
  excludes(deepView, "最新结果");
  excludes(deepView, "deep-run-workflow-active");
  excludes(deepView, "deep-run-workflow-complete");

  includes(transcriptTimeline, "selectedItemKey");
  includes(transcriptTimeline, "onSelectItem");
  includes(transcriptTimeline, "data-selected");
  includes(transcriptTimeline, "aria-pressed={selected}");
  includes(transcriptTimeline, "agent-activity-body");
  includes(transcriptTimeline, 'aria-label="工作进度"');

  includes(deepStyles, ".with-work-detail");
  includes(deepStyles, ".deep-plan-confirmation");
  includes(deepStyles, ".deep-run-transcript");
  includes(deepStyles, ".deep-run-transcript-thread");
  includes(deepStyles, ".deep-run-child-list");
  includes(deepStyles, ".deep-run-child-list-item");
  includes(deepStyles, ".deep-run-child-list-signal");
  includes(deepStyles, ".deep-work-detail-panel");
  includes(deepStyles, ".deep-work-detail-meta button");
  includes(deepStyles, ".deep-work-detail-workline");
  includes(deepStyles, ".deep-child-agent-workflow");
  includes(deepStyles, ".deep-child-agent-model-output");
  includes(deepStyles, ".deep-child-agent-tool-group");
  includes(deepStyles, ".deep-work-detail-actionbar");
  includes(deepStyles, ".deep-work-detail-composer");
  includes(deepStyles, ".deep-child-task-approval");
  includes(deepStyles, ".deep-compact-conclusion");
  includes(deepStyles, ".deep-compact-conclusion-actions");
  includes(deepStyles, ".deep-compact-conclusion-note");
  includes(deepStyles, ".deep-runtime-health-notice");
  excludes(deepStyles, ".deep-run-console");
  excludes(deepStyles, ".deep-run-transcript-activity-block");
  excludes(deepStyles, ".deep-run-workflow");
  excludes(deepStyles, ".deep-run-console-kicker");
  excludes(deepStyles, ".deep-run-console-goal-icon");
  excludes(deepStyles, ".deep-run-workflow .agent-activity-chip.meta");
  excludes(deepStyles, ".with-task-sidebar");
  excludes(deepStyles, ".deep-task-sidebar");
  excludes(deepStyles, ".with-workflow-detail");
  excludes(deepStyles, ".deep-parent-workflow-pane");
  excludes(deepStyles, ".deep-parent-workflow-list");
  excludes(deepStyles, ".deep-child-node-approval");
  excludes(deepStyles, ".with-node-inspector");
  excludes(deepStyles, ".deep-collaboration-node-index");
  excludes(deepStyles, ".deep-node-inspector");
  excludes(deepStyles, ".deep-tree-live-map");
  excludes(deepStyles, ".deep-tree-live-node");
  excludes(deepStyles, ".deep-flow-canvas");
  excludes(deepStyles, ".deep-work-detail-timeline");
  excludes(deepStyles, ".deep-work-detail-step");
  excludes(deepStyles, ".deep-run-child-card");
  excludes(deepStyles, ".deep-run-child-grid");
  excludes(deepStyles, ".deep-run-child-section");
  excludes(deepStyles, ".deep-run-result");
  excludes(deepStyles, ".deep-run-workflow-active");
  excludes(deepStyles, ".deep-run-workflow-complete");
  excludes(deepStyles, ".deep-run-workflow-item");
  excludes(deepStyles, ".deep-workline-title");
  excludes(deepStyles, ".deep-work-detail-footnote");
  excludes(deepStyles, ".deep-workline-spin");
});

test("deep transcript blocks keep a single narrative with stale conclusion recovery", async () => {
  const deepView = await readPanelUiSource(path.join("components", "deep-view.tsx"));

  includes(deepView, "const synthesisText = parentSynthesisText(view);");
  includes(deepView, "const conclusionText = parentConclusionText(view.report?.conclusion, view.liveProjection.conclusion);");
  includes(deepView, "const staleConclusion = conclusionNeedsResynthesis(view, conclusionText);");
  includes(deepView, "const decisionComesBeforeChildren = managerDecisionComesBeforeChildren(view);");
  includes(deepView, "if (synthesisText !== undefined && conclusionText === undefined)");
  includes(deepView, 'kind: "conclusion"');
  includes(deepView, 'staleMessage: staleConclusion ? "协作材料已更新，当前结论待重新综合。" : undefined');
  includes(deepView, "const notice = parentNotice(view);");
  excludes(deepView, "for (const child of children)");
  excludes(deepView, 'kind: "result_text"');
  excludes(deepView, "return mergeAdjacentAssistantTextBlocks(blocks);");
  excludes(deepView, "function mergeAssistantText");
  excludes(deepView, "这个目标还缺少关键范围");
});

test("child detail workflow renders model output and collapsed desktop Agent tool groups", async () => {
  const [deepView, deepContract, childRunner, deepRuntime, deepReadModel, treeAttachment] = await Promise.all([
    readPanelUiSource(path.join("components", "deep-view.tsx")),
    readPanelUiSource(path.join("contracts", "deep.ts")),
    readAppSource(path.join("deep", "deep-child-agent-runner.ts")),
    readAppSource(path.join("deep", "deep-runtime.ts")),
    readAppSource(path.join("deep", "deep-read-model.ts")),
    readAppSource("agent-run-tree-attachment.ts"),
  ]);

  includes(deepView, "displayActivityItemsForNodes([node])");
  includes(deepView, "display: call.display");
  includes(deepView, "view={detailTimelineView(segment.items)}");
  includes(deepView, "collapsed={true}");
  includes(deepView, "<RichText text={segment.text} />");
  includes(deepView, "const messageText = childModelMessageText(message);");
  includes(deepView, "const resultText = childMaterialResultText(child);");
  includes(deepView, "return child.latestResult === undefined || result === undefined ? undefined : compactWorklineText(result, 120);");
  includes(deepView, "return visibleWorkflowStatusLabel(item.status);");
  excludes(deepView, "childModelMessageText(message) ?? childModelToolCallDecisionText");
  excludes(deepView, "模型工具调用决策");
  includes(deepView, "function mergeExpandedSections");
  includes(deepView, "function mergeActivityBadges");
  includes(deepContract, "import type { ToolDisplayProjection } from \"./tools\";");
  includes(deepContract, "readonly display?: ToolDisplayProjection;");
  includes(childRunner, "display: toolCall.projection?.display ?? toolCall.projection?.envelope?.uiDisplay");
  excludes(deepRuntime, "模型发起");
  excludes(deepReadModel, "模型发起");
  includes(treeAttachment, "readonly display?: ToolDisplayProjection;");
});

function includes(source: string, pattern: string): void {
  if (!source.includes(pattern)) {
    throw new Error(`Expected source to include: ${pattern}`);
  }
}

function excludes(source: string, pattern: string): void {
  if (source.includes(pattern)) {
    throw new Error(`Expected source to exclude: ${pattern}`);
  }
}
