export const STREAM_TYPES = [
  "run.started",
  "run.cancelled",
  "run.blocked",
  "run.resumed",
  "agent.note.delta",
  "agent.note.completed",
  "model.output.delta",
  "model.output.completed",
  "tool.requested",
  "tool.completed",
  "tool.failed",
  "confirmation.needed",
  "user_approval.received",
  "user.guidance",
  "agent.delegation.planned",
  "agent.child.started",
  "agent.child.completed",
  "agent.child.waiting",
  "agent.parent_synthesis.completed",
  "final.result",
  "run.failed"
];

export const STATUS_LABELS = {
  pending: "待开始",
  queued: "排队中",
  planning: "准备中",
  running: "正在工作",
  approval_needed: "需要确认",
  needs_input: "需要补充",
  paused: "已暂停",
  completed: "已完成",
  failed: "未完成",
  cancelled: "已取消",
  blocked: "需要处理",
  sent: "已发送"
};

export const EVENT_LABELS = {
  "run.started": "开始工作",
  "run.cancelled": "已取消",
  "run.blocked": "需要处理",
  "run.resumed": "继续工作",
  "agent.note.delta": "工作笔记",
  "agent.note.completed": "工作笔记",
  "model.output.delta": "正在生成内容",
  "model.output.completed": "内容已整理",
  "tool.requested": "正在读取材料",
  "tool.completed": "材料已读取",
  "tool.failed": "工具执行失败",
  "confirmation.needed": "需要确认",
  "user_approval.received": "收到确认结果",
  "user.guidance": "用户指导",
  "agent.delegation.planned": "安排检查",
  "agent.child.started": "检查开始",
  "agent.child.completed": "检查完成",
  "agent.child.waiting": "等待结果",
  "agent.parent_synthesis.completed": "汇总判断",
  "final.result": "最终结果",
  "run.failed": "运行失败"
};

export function createPanelState() {
  return {
    config: undefined,
    capabilities: undefined,
    informationAccess: undefined,
    tools: undefined,
    skills: [],
    workspace: undefined,
    currentConversationId: undefined,
    currentRunId: undefined,
    pendingConfirmation: undefined,
    queuedRunIds: new Set(),
    eventSource: undefined,
    pollingTimer: undefined,
    seenSequences: new Set(),
    lastSequence: 0,
    lastFocusedTerminalRunId: undefined,
    conversations: [],
    assistantEntry: undefined,
    assistantStageKey: undefined,
    assistantStreamBuffer: "",
    assistantStreamTimer: undefined,
    assistantControlBuffer: "",
    inspectorTab: "overview",
    settingsTab: "model",
    isSubmitting: false
  };
}

export function collectPanelDom() {
  return {
    runStatus: document.getElementById("runStatus"),
    transcriptWrap: document.getElementById("transcriptWrap"),
    runMetrics: document.getElementById("runMetrics"),
    mainCanvas: document.getElementById("mainCanvas"),
    transcript: document.getElementById("transcript"),
    introBlock: document.getElementById("introBlock"),
    workspaceEmptyPrompt: document.getElementById("workspaceEmptyPrompt"),
    workspaceEmptyText: document.getElementById("workspaceEmptyText"),
    workspaceEmptySelectButton: document.getElementById("workspaceEmptySelectButton"),
    intentField: document.getElementById("intentField"),
    composerBox: document.querySelector(".composer-box"),
    goalInput: document.getElementById("goalInput"),
    contextRefsInput: document.getElementById("contextRefsInput"),
    permissionRefsInput: document.getElementById("permissionRefsInput"),
    runModeInput: document.getElementById("runModeInput"),
    aiMode: document.getElementById("aiMode"),
    providerHint: document.getElementById("modelHint"),
    inputStatusDot: document.querySelector(".input-status-dot"),
    runButton: document.getElementById("runButton"),
    deepRunButton: document.getElementById("deepRunButton"),
    cancelRunButton: document.getElementById("cancelRunButton"),
    newRunButton: document.getElementById("newRunButton"),
    skillsButton: document.getElementById("skillsButton"),
    toolsButton: document.getElementById("toolsButton"),
    sidebarToggleButton: document.getElementById("sidebarToggleButton"),
    shell: document.getElementById("shell"),
    runHistory: document.getElementById("runHistory"),
    sessionTitle: document.getElementById("sessionTitle"),
    profileMenuButton: document.getElementById("profileMenuButton"),
    accountMenu: document.getElementById("accountMenu"),
    accountProfileButton: document.getElementById("accountProfileButton"),
    accountSettingsButton: document.getElementById("accountSettingsButton"),
    accountDiagnosticsButton: document.getElementById("accountDiagnosticsButton"),
    accountMenuNote: document.getElementById("accountMenuNote"),
    drawerBackdrop: document.getElementById("drawerBackdrop"),
    developerDrawer: document.getElementById("developerDrawer"),
    settingsBackdrop: document.getElementById("settingsBackdrop"),
    settingsPanel: document.getElementById("settingsPanel"),
    providerPresetInput: document.getElementById("providerPresetInput"),
    presetModelHint: document.getElementById("presetModelHint"),
    baseUrlInput: document.getElementById("baseUrlInput"),
    modelInput: document.getElementById("modelInput"),
    defaultAiModeInput: document.getElementById("defaultAiModeInput"),
    apiKeyInput: document.getElementById("apiKeyInput"),
    saveConfigButton: document.getElementById("saveConfigButton"),
    configStatus: document.getElementById("configStatus"),
    webSearchProviderInput: document.getElementById("webSearchProviderInput"),
    tavilyKeyInput: document.getElementById("tavilyKeyInput"),
    tavilyMaxResultsInput: document.getElementById("tavilyMaxResultsInput"),
    workspaceDirectoryInput: document.getElementById("workspaceDirectoryInput"),
    selectWorkspaceDirectoryButton: document.getElementById("selectWorkspaceDirectoryButton"),
    saveWorkspaceConfigButton: document.getElementById("saveWorkspaceConfigButton"),
    workspaceConfigStatus: document.getElementById("workspaceConfigStatus"),
    saveToolConfigButton: document.getElementById("saveToolConfigButton"),
    toolConfigStatus: document.getElementById("toolConfigStatus"),
    mcpConfigStatus: document.getElementById("mcpConfigStatus"),
    skillsList: document.getElementById("skillsList"),
    inspectorTabs: Array.from(document.querySelectorAll(".inspector-tab")),
    inspectorPanels: Array.from(document.querySelectorAll(".inspector-panel")),
    settingsTabs: Array.from(document.querySelectorAll("[data-settings-tab]")),
    settingsPanels: Array.from(document.querySelectorAll("[data-settings-panel]")),
    railStatusBadge: document.getElementById("railStatusBadge"),
    runPath: document.getElementById("runPath"),
    supervisionStatus: document.getElementById("supervisionStatus"),
    failurePanel: document.getElementById("failurePanel"),
    flowList: document.getElementById("flowList"),
    agentTree: document.getElementById("agentTree"),
    agentInspector: document.getElementById("agentInspector"),
    parentSynthesis: document.getElementById("parentSynthesis"),
    riskPanel: document.getElementById("riskPanel"),
    debugList: document.getElementById("debugList"),
    debugJson: document.getElementById("debugJson")
  };
}
