import type { ModelProviderPreset } from "./contracts.js";

export const BUILTIN_MODEL_PROVIDER_PRESETS: readonly ModelProviderPreset[] = [
  {
    presetId: "openai",
    label: "OpenAI",
    vendor: "OpenAI",
    description: "OpenAI GPT 模型服务，模型列表来自 /v1/models。",
    providerKind: "openai_compatible",
    protocolKind: "openai_responses",
    baseUrl: "https://api.openai.com/v1",
    modelsPath: "/models",
    regionLabel: "全球",
    docsUrl: "https://platform.openai.com/docs",
  },
  {
    presetId: "claude",
    label: "Anthropic",
    vendor: "Anthropic",
    description: "Claude 原生 Messages API，模型列表来自 /v1/models。",
    providerKind: "anthropic",
    protocolKind: "anthropic_messages",
    baseUrl: "https://api.anthropic.com",
    modelsPath: "/v1/models",
    regionLabel: "全球",
    docsUrl: "https://docs.anthropic.com/",
  },
  {
    presetId: "deepseek",
    label: "DeepSeek",
    vendor: "DeepSeek",
    description: "DeepSeek OpenAI-compatible 接口，适合通用对话、代码和工具调用场景。",
    providerKind: "openai_compatible",
    protocolKind: "openai_responses",
    baseUrl: "https://api.deepseek.com",
    modelsPath: "/models",
    regionLabel: "全球",
    docsUrl: "https://api-docs.deepseek.com/",
  },
  {
    presetId: "moonshot",
    label: "月之暗面",
    vendor: "Moonshot AI",
    description: "月之暗面 Kimi 国内 OpenAI-compatible 接口。",
    providerKind: "openai_compatible",
    protocolKind: "openai_responses",
    baseUrl: "https://api.moonshot.cn/v1",
    modelsPath: "/models",
    regionLabel: "国内",
    docsUrl: "https://platform.moonshot.cn/docs/guide/start-using-kimi-api",
  },
  {
    presetId: "glm",
    label: "智谱 AI",
    vendor: "智谱 AI",
    description: "GLM / BigModel OpenAI-compatible 接口。",
    providerKind: "openai_compatible",
    protocolKind: "openai_responses",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    modelsPath: "/models",
    regionLabel: "国内",
    docsUrl: "https://docs.bigmodel.cn/",
  },
  {
    presetId: "minimax",
    label: "MiniMax",
    vendor: "MiniMax",
    description: "MiniMax 国内 OpenAI-compatible 接口。",
    providerKind: "openai_compatible",
    protocolKind: "openai_responses",
    baseUrl: "https://api.minimaxi.com/v1",
    modelsPath: "/models",
    regionLabel: "国内",
    docsUrl: "https://platform.minimax.io/docs/api-reference/text-chat-openai",
  },
];

export function listBuiltinModelProviderPresets(): readonly ModelProviderPreset[] {
  return BUILTIN_MODEL_PROVIDER_PRESETS.map((preset) => ({ ...preset }));
}
